name: skyesite-dev
channels:
  - conda-forge
dependencies:
  # -- PROD -- #
  - python=3.13.5
  - pelican
  # -- DEV -- #
  - black
  - flake8
  # -- PROD.PIP -- #
  - pip
  - pip:
    - ghp-import
    - pelican-seo
    - pelican-sitemap
    - pelican-share-post
    - pelican-webassets
    - pelican-search
    - pelican-precompress